apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app
  namespace: dev
spec:
  selector:
    matchLabels:
      app: playground-app
  replicas: 1
  template:
    metadata:
      labels:
        app: playground-app
    spec:
      containers:
      - name: playground-app
        image: wil42/playground:v2
        ports:
        - containerPort: 8888

